### ISSUE TITLE
Null Reference with connected storage in Unity

### ISSUE THREAD

**Issue by DutyStudios** [Microsoft/xbox-live-unity-plugin#124] opened 2017-09-08 03:25 UTC
Hello I am getting this error message below and I'm not too sure why. Do you have an idea of where I should look? Also do you know if there is an example anywhere of using connected storage with Unity and the creator's program?

NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Xbox.Services.ConnectedStorage.GameSaveHelper.<GetAsStrings>d__5.MoveNext()
   at UnityEngine.SetupCoroutine.InvokeMoveNext(IEnumerator enumerator, IntPtr returnValueAddress)
   at UnityEngine.SetupCoroutine.$Invoke1InvokeMoveNext(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method) 
(Filename: <Unknown> Line: 0)

**Comment by tecraveiro** [comment] 2017-09-08 13:54
I get a similar error on sign in already (using the SignInAndProfile scene):

'XBLSignInPluginTest.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'D:\Builds\XBLSignInPluginTest\XBLSignInPluginTest\bin\x64\Debug\AppX\System.Collections.Concurrent.dll'. Cannot find or open the PDB file.
Warning: unknown type TaskYieldInstruction`1[Microsoft.Xbox.Services.SignInResult] detected. Using reflection to gather its type information. Consider to reference it from your scripts so it can gathered during the build process.
 
(Filename: C:\buildslave\unity\build\Runtime/ScriptingBackend/DotNet/ScriptingTypeProvider_DotNet.cpp Line: 153)

Exception thrown: 'System.NullReferenceException' in Microsoft.Xbox.Services.UWP.CSharp.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.NullReferenceException' in System.Private.CoreLib.ni.dll
Exception thrown: 'System.AggregateException' in Assembly-CSharp.dll
'XBLSignInPluginTest.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'D:\Builds\XBLSignInPluginTest\XBLSignInPluginTest\bin\x64\Debug\AppX\System.Diagnostics.StackTrace.dll'. Cannot find or open the PDB file.
AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
   at TaskYieldInstruction.get_keepWaiting()
   at UnityEngine.SetupCoroutine.InvokeMoveNext(IEnumerator enumerator, IntPtr returnValueAddress)
   at UnityEngine.SetupCoroutine.$Invoke1InvokeMoveNext(Int64 instance, Int64* args)
   at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance, Int64* args, IntPtr method) 
(Filename: <Unknown> Line: 0)

Does sign in work for you at all? I'm pointing to the right Sandbox and everything.

**Comment by DutyStudios** [comment] 2017-09-08 15:03
Yes, I think I just put the prefab in my scene that I want them to login with. When I am home later I will take a look and get back with you. If I remember correctly there are two prefab you want on the scene...

Also I am using the 1707 or QFE  1 release. I haven't tested with the most recent.

**Comment by tecraveiro** [comment] 2017-09-08 15:26
Cheers, I've solved my sign in problem.

The standard silent sign in is very unreliable, commenting out the code for it and using SignInAsync() instead of SignInSilentlyAsync() in UserProfile works fine. 

MS guys, please do not try to be fancy and keep the sample as basic as possible and maybe comment the different ways to sign in better. Maintaining this doc would be a good start: https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-creators/sign-in-to-xbox-live-in-unity

Thanks, Stackoverflow: https://stackoverflow.com/questions/42586752/xbox-live-user-sign-in-failed-on-xbox-one

DutyStudios, I'm tackling save games and connected storage next so I will let you know how I get on and if I encounter the same error. 

You are following the guide, right? https://docs.microsoft.com/en-us/windows/uwp/xbox-live/storage-platform/connected-storage/connected-storage-saving#sample 
Wished they had a more detailed step-by-step guide for this using the sample, too, since it's a very complex topic.

**Comment by DutyStudios** [comment] 2017-09-08 15:33
Awesome, glad you were able to figure yours out! Is it possible for us to
use that guide even though we are using C#? That guide is for c++ right?
I've been trying to piece it together based off of what the code is doing
from the C# code they've integrated.

**Comment by MSFT-Heba** [comment] 2017-09-08 15:41
Regarding the sign-in behavior, the recommended behavior is to attempt to Sign-In Silently first (that way your user doesn't have to sign-in again every time you get into that scene) and if that fails, Sign-In should be called instead. 

As for the Connected Storage, the best sample (if you're using this Unity-Plugin) is to look at the :
'GameSave' Folder > Examples. That example scene shows the 'GameSaveUI' prefab which is actually an example of how to use 'GameSaveHelper', the actual script that you can use to integrate with Connected Storage.

**Comment by MSFT-Heba** [comment] 2017-09-08 15:41
DutyStudios, would you mind sharing the code you're using to integrate with Connected Storage? How're you setting it up?

**Comment by DutyStudios** [comment] 2017-09-08 15:46
Thanks for your input @MSFT-Heba as soon as I get home today I will post it here.

**Comment by DutyStudios** [comment] 2017-09-09 04:22
Ok, so I was trying to set this up to auto load and save the game data like so...

I first altered the GameSaveUI.cs file here so that I could call this variable from other classes.

    //private GameSaveHelper gameSaveHelper;
    public GameSaveHelper gameSaveHelper;

Then I saved my variables here in the save method like so...

    public void SaveData()
    {
        if (this.gameSaveHelper.IsInitialized())
        {
            try
            {
                var contentToSave = new Dictionary<string, byte[]>
                {
                    {this.GameSaveBlobName, Encoding.UTF8.GetBytes(this.gameData.ToString())},
                    {CampaignScore.ToString(),Encoding.UTF8.GetBytes(this.gameData.ToString())},
                    {HardScore.ToString(),Encoding.UTF8.GetBytes(this.gameData.ToString())},
                    {BossScore.ToString(),Encoding.UTF8.GetBytes(this.gameData.ToString())},
                    {EndlessScore.ToString(),Encoding.UTF8.GetBytes(this.gameData.ToString())},
                    {LevelManager.continueString,Encoding.UTF8.GetBytes(this.gameData.ToString())}
                };

                this.StartCoroutine(this.gameSaveHelper.SubmitUpdates(this.GameSaveContainerName, contentToSave, null,
                    saveResultStatus =>
                    {
                        this.LogLine(
                                saveResultStatus == GameSaveStatus.Ok
                                    ? string.Format("Saved data : {0}", this.gameData)
                                    : string.Format("SaveDataForUser failed: {0}", saveResultStatus));
                    }));

            }
            catch (Exception ex)
            {
                this.LogLine("SaveDataForUser failed: " + ex.Message);
            }
        }
        else
        {
            this.LogLine("Game Save Helper hasn't been initialized yet. Please Sign In first.");
        }
    }

My load method looks like this...

    public void LoadData()
    {
        if (this.gameSaveHelper.IsInitialized())
        {
            try
            {
                this.StartCoroutine(this.gameSaveHelper.GetAsStrings(this.GameSaveContainerName, new[] { this.GameSaveBlobName },
                    loadResultDictionary =>
                    {
                        try
                        {
                            var blobLoadResult = loadResultDictionary[this.GameSaveBlobName];
#if !UNITY_EDITOR
                            this.gameData = int.Parse(blobLoadResult);
#endif
                            this.LogLine(string.Format("Loaded data : {0}", this.gameData));
                            Debug.Log(blobLoadResult);

                        }
                        catch (Exception ex)
                        {
                            this.LogLine(ex.Message);
                        }
                    }));
            }
            catch (Exception ex)
            {
                this.LogLine("LoadData failed: " + ex.Message);
            }
        }
        else
        {
            this.LogLine("Game Save Helper hasn't been initialized yet. Please Sign In first.");
        }
    }

I load the data automatically in my levelmanager.cs file.... first I initialize save on the start screen...

    private void InitializeSave()
    {
        if (!gameSaveUI.gameSaveHelper.IsInitialized())
        {
            gameSaveUI.InitializeSaveSystem();
            Invoke("InitializeSave", 3f);
        }
    }
Once that is initialized I try to load the data...

    void Update()
    {
        if (SceneManager.GetActiveScene().buildIndex == 1)     
        {
            if (Input.GetKeyDown(KeyCode.Escape))
            {
                Application.Quit();
            }

            if (!GameLoaded && gameSaveUI.gameSaveHelper.IsInitialized())
            {
                GameLoaded = true;
                gameSaveUI.LoadData();                
            }
So it seems like everytime after loading I then get the error mentioned in the first comment.

**Comment by DutyStudios** [comment] 2017-09-09 05:55
I think I found out what was wrong with this particular error. I think the main thing it was complaining about is that there was no save data to load. I had to mess with the save method a bit and make sure it saved once. Then I no longer got the error. You can close the issue unless you have something else to include or comment @MSFT-Heba. Thank you. I'm still a bit lost on how to actually save and then load and assign the variables I need saved and then loaded to.

**Comment by tecraveiro** [comment] 2017-09-09 13:05
> Regarding the sign-in behavior, the recommended behavior is to attempt to Sign-In Silently first (that way your user doesn't have to sign-in again every time you get into that scene) and if that fails, Sign-In should be called instead.

@MSFT-Heba: The issue is that silent async sign in simply crashes out with a NullReferenceException and I have no way of finding out why, if the sample at least handled it gracefully, I could keep it in.

"Warning: unknown type TaskYieldInstruction`1[Microsoft.Xbox.Services.SignInResult] detected. Using reflection to gather its type information. "

 Is that what the newest on master is supposed to fix? Would be time for a new release, then. I'm using the 1707 QFE 3 Release.

**Comment by MSFT-Heba** [comment] 2017-09-14 20:34
@DutyStudios: Glad to hear your issue is resolved. Do let us know if you have more questions.

@tecraveiro:  Could you try switching to .Net for the backend and .NET 2.0 for the compatibility level? Please let us know how this works out as it could be an issue with integrating with IL2CPP.

The silent sign-in loads the same XboxLiveUser as normal sign-in. What this allows you to do compared to normal sign-in, is once the user signs in for the first time into your game, if you reload this scene again, the user will already be signed in and won't need to sign in again. The sign-in UI won't need to pop up again. If you only use sign-in, then the sign-in UI will pop for the user every time they get into the scene.

**Comment by tecraveiro** [comment] 2017-09-15 11:25
@MSFT-Heba Silent sign-in does indeed work with .Net and .NET 2.0
(non-subset).

I'm usually building with .Net. I cannot use IL2CPP since I then get Unity
build errors with Task Extensions and List<>, etc.

**Comment by tecraveiro** [comment] 2017-09-15 11:43
@MSFT-Heba About connected storage and serialization:
What is the recommended way for this? I am trying DataContractSerialization for my save game object which works ok if I write it as a file to disc as XML (and load it the same way) but I get a NullReferenceException with Connected Storage when calling the Subroutine  "this.StartCoroutine(this.gameSaveHelper.SubmitUpdates"

Saving:
```
[...]
        if (this.gameSaveHelper.IsInitialized())
        {
            try
            {
                DataContractSerializer serializer = new DataContractSerializer(typeof(DataSlot));
                MemoryStream stream = new MemoryStream();
                serializer.WriteObject(stream, dataSlot);
                byte[] byteArray = stream.ToArray();

                // TODO: Remove this, just testing output for connected storage
                UnityEngine.Windows.File.WriteAllBytes(Application.persistentDataPath + "/" + GetSaveSlotName(currentSaveSlot), byteArray);


                // Using save slot name as blob name
                var contentToSave = new Dictionary<string, byte[]>
                                    {
                                        {
                                            GetSaveSlotName(currentSaveSlot),
                                            byteArray
                                        }
                                    };

                // Submit updates to "DataSlots" container
                this.StartCoroutine(this.gameSaveHelper.SubmitUpdates(dataSlotContainerName, contentToSave, null,
                    saveResultStatus =>
                    {
                        Debug.Log(
                                saveResultStatus == GameSaveStatus.Ok
                                    ? string.Format("Connected Storage - Saved data for slot {0}", currentSaveSlot)
                                    : string.Format("Connected Storage - SaveDataForUser failed: {0}", saveResultStatus));
                    }));

            }
            catch (Exception ex)
            {
                 Debug.Log("SaveDataForUser failed: " + ex.Message);
            }
        }
        else
        {
             Debug.Log("XBL Game Save Helper hasn't been initialized yet. Please Sign In first.");
        }
[...]
```

Loading:
```
[...]
        DataSlot loadDataSlot = new DataSlot();
        if (this.gameSaveHelper.IsInitialized())
        {
            try
            {
                DataContractSerializer serializer = new DataContractSerializer(typeof(SerializeOptionsClass));  

                //Read as bytes or strings?
                this.StartCoroutine(this.gameSaveHelper.GetAsBytes(dataSlotContainerName, new[] { GetSaveSlotName(saveSlot) },
                    loadResultDictionary =>
                    {
                        try
                        {
                            var blobLoadResult = loadResultDictionary[GetSaveSlotName(saveSlot)];
    #if !UNITY_EDITOR
                            if (blobLoadResult.Length != 0) {
                                MemoryStream stream = new MemoryStream(blobLoadResult);
                            loadDataSlot = (DataSlot)serializer.ReadObject(stream); 
                            }
    #endif
                            Debug.LogFormat("Loaded data for save slot: {0}", saveSlot);
                        }
                        catch (Exception ex)
                        {
                            Debug.Log(ex.Message);
                        }
                    }));
            }
            catch (Exception ex)
            {
                Debug.Log("LoadData failed: " + ex.Message);
            }
        }
        else
        {
            Debug.Log("Game Save Helper hasn't been initialized yet. Please Sign In first.");
        }
        loadDataSlot.UpdateArraySizesIfRequired();
        if(doPostLoad){
            loadDataSlot.gameStats.postLoad();
        }
[...]
```

More complex real-world examples than those in the samples would be really welcome.

**Comment by MSFT-Heba** [comment] 2017-09-25 17:35
@tecraveiro : After looking at the code you shared, I can't seem to spot where you are initializing the gameSaveHelper.

Could you double check that you're doing the following somewhere in your Start() perhaps?
this.gameSaveHelper = new GameSaveHelper();

Otherwise gameSaveHelper will always be null and will never initialize.

Could you please update us if that was indeed the issue?

**Comment by tecraveiro** [comment] 2017-09-25 19:03
Yes, it was. Thanks.

**Comment by MSFT-Heba** [comment] 2017-09-25 19:14
Great. We'll be closing the issue for now. Feel free to reopen if you have more questions.

Thanks everyone.

**Closed by MSFT-Heba** 2017-09-25 19:14 UTC
