### ISSUE TITLE
Xbox Live user sign-in (Un-solved)

### ISSUE THREAD

**Issue by johnrlisenby** [Microsoft/xbox-live-unity-plugin#142] opened 2017-10-19 13:58 UTC
Hello,
I have upgraded my project to Unity 2017.2f3 and Windows Fall CC Update, and now I'm getting error ArgumentNullException: Argument cannot be null.
Parameter name: s at UserProfile error here around 218 line:  
private IEnumerator LoadProfileInfo()
    {
   -->     var userId = ulong.Parse(this.XboxLiveUser.User.XboxUserId);

I get the message in the Unity editor and when I build and playtest the game. I am using the latest plug-in. Not sure if this is a new bug or if I done something wrong, but there was no issues before I upgraded.

Thanks,
John

**Comment by ayubhassan** [comment] 2017-10-19 20:23
does this error happen when switching between scenes?

**Comment by johnrlisenby** [comment] 2017-10-19 21:11
Hi,
No, it only happens in the main scene where I have the user login into Xbox Live. I can progress forward, but I get the same error when I come back to that same scene (Main).

I reloaded loaded the plug in and getting the same error.

Thanks,

John

**Comment by ayubhassan** [comment] 2017-10-19 22:10
I had the same problem when switching between scenes or reloading the same scenes. And the problem is the script “userprofile.cs” is getting destroyed when you leave the first scene. Just add a “dontdestroythisonload” to that script’s awake function.

**Comment by johnrlisenby** [comment] 2017-10-20 12:55
Thanks for the reply, 
No, I am getting the error when my scene starts up with the Xbox prefabs in them. It seem that the user is signed in. I get the debug log "[Singleton] XboxLiveUserManager was created with DontDestroyOnLoad."  I have a bool (around line 197) that check for successfully log in, and they are signed in. But I'm getting the null message. The issue started after I upgraded OS and Unity 2017.2. The error and script is below. 

Thanks for your help,

John

 `ArgumentNullException: Argument cannot be null.
Parameter name: s
System.UInt64.Parse (System.String s, NumberStyles style, IFormatProvider provider) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/UInt64.cs:351)
System.UInt64.Parse (System.String s) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/UInt64.cs:99)
UserProfile+<LoadProfileInfo>c__Iterator2.MoveNext () (at Assets/Xbox Live/Scripts/UserProfile.cs:217)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)`

Here is the userprofile script `// Copyright (c) Microsoft Corporation
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// 

using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Threading.Tasks;

using Microsoft.Xbox.Services;
using Microsoft.Xbox.Services.Social.Manager;

using UnityEngine;
using UnityEngine.UI;

public class UserProfile : MonoBehaviour
{
    public XboxLiveUserInfo XboxLiveUser;

    public string InputControllerButton;

    private bool SignInCalledOnce;

    [HideInInspector]
    public GameObject signInPanel;

    [HideInInspector]
    public GameObject profileInfoPanel;

    [HideInInspector]
    public Image gamerpic;

    [HideInInspector]
    public Image gamerpicMask;

    [HideInInspector]
    public Text gamertag;

    [HideInInspector]
    public Text gamerscore;

    [HideInInspector]
    public XboxLiveUserInfo XboxLiveUserPrefab;

    public bool AllowGuestAccounts = false;

    public void Awake()
    {
        this.EnsureEventSystem();
        XboxLiveServicesSettings.EnsureXboxLiveServicesSettings();

        if (!XboxLiveUserManager.Instance.IsInitialized)
        {
            XboxLiveUserManager.Instance.Initialize();
        }

        XboxLive.Instance.PresenceWriter.StartWriter();

    }

    public void Start()
    {
        // Disable the sign-in button if there's no configuration available.
        if (XboxLive.Instance.AppConfig == null || XboxLive.Instance.AppConfig.AppId == null)
        {
            Button signInButton = this.signInPanel.GetComponentInChildren<Button>();
            signInButton.interactable = false;
            this.profileInfoPanel.SetActive(false);
            Text signInButtonText = signInButton.GetComponentInChildren<Text>(true);
            if (signInButtonText != null)
            {
                signInButtonText.fontSize = 16;
                signInButtonText.text = "Xbox Live is not enabled.\nSee errors for detail.";
            }
        }

        if (XboxLiveUserManager.Instance.SingleUserModeEnabled)
        {
            if (XboxLiveUserManager.Instance.UserForSingleUserMode == null)
            {
                XboxLiveUserManager.Instance.UserForSingleUserMode = Instantiate(this.XboxLiveUserPrefab);
                this.XboxLiveUser = XboxLiveUserManager.Instance.UserForSingleUserMode;
                if (XboxLive.Instance.AppConfig != null && XboxLive.Instance.AppConfig.AppId != null)
                {
                    this.SignIn();
                }
            }
            else {
                this.XboxLiveUser = XboxLiveUserManager.Instance.UserForSingleUserMode;
                this.StartCoroutine(this.LoadProfileInfo());
            }
        }


        this.Refresh();
    }

    private void XboxLiveUserOnSignOutCompleted(object sender, SignOutCompletedEventArgs signOutCompletedEventArgs)
    {
        this.Refresh();
    }

    public void SignIn()
    {
        this.StartCoroutine(this.InitializeXboxLiveUser());
    }

    public void Update()
    {
        if (XboxLiveUserManager.Instance.SingleUserModeEnabled && XboxLiveUserManager.Instance.UserForSingleUserMode != null
            && XboxLiveUserManager.Instance.UserForSingleUserMode.User != null
            && !XboxLiveUserManager.Instance.UserForSingleUserMode.User.IsSignedIn && !this.SignInCalledOnce)
        {
            this.SignInCalledOnce = true;
            this.StartCoroutine(this.SignInAsync());
        }

        if (this.XboxLiveUser != null && this.XboxLiveUser.User != null && !this.XboxLiveUser.User.IsSignedIn && !this.SignInCalledOnce)
        {
            this.SignInCalledOnce = true;
            this.StartCoroutine(this.SignInAsync());
        }

        if (!this.SignInCalledOnce && !string.IsNullOrEmpty(this.InputControllerButton) && Input.GetKeyDown(this.InputControllerButton))
        {
            this.StartCoroutine(this.InitializeXboxLiveUser());
        }

    }

    public IEnumerator InitializeXboxLiveUser()
    {
        yield return null;

        // Disable the sign-in button
        this.signInPanel.GetComponentInChildren<Button>().interactable = false;

#if ENABLE_WINMD_SUPPORT
        if (!XboxLiveUserManager.Instance.SingleUserModeEnabled && this.XboxLiveUser != null && this.XboxLiveUser.WindowsSystemUser == null)
        {
            var autoPicker = new Windows.System.UserPicker { AllowGuestAccounts = this.AllowGuestAccounts };
            autoPicker.PickSingleUserAsync().AsTask().ContinueWith(
                    task =>
                        {
                            if (task.Status == TaskStatus.RanToCompletion)
                            {
                                this.XboxLiveUser.WindowsSystemUser = task.Result;
                                this.XboxLiveUser.Initialize();
                            }
                            else
                            {
                                if (XboxLiveServicesSettings.Instance.DebugLogsOn)
                                {
                                    Debug.Log("Exception occured: " + task.Exception.Message);
                                }
                            }
                        });
        }
        else
        {
            if (this.XboxLiveUser == null)
            {
                this.XboxLiveUser = XboxLiveUserManager.Instance.UserForSingleUserMode;
            }
            if (this.XboxLiveUser.User == null)
            {
                this.XboxLiveUser.Initialize();
            }
        }
#else
        if (XboxLiveUserManager.Instance.SingleUserModeEnabled && this.XboxLiveUser == null)
        {
            this.XboxLiveUser = XboxLiveUserManager.Instance.GetSingleModeUser();
        }

        this.XboxLiveUser.Initialize();
#endif
    }

    public IEnumerator SignInAsync()
    {
        SignInStatus signInStatus;
        TaskYieldInstruction<SignInResult> signInSilentlyTask = this.XboxLiveUser.User.SignInSilentlyAsync().AsCoroutine();
        yield return signInSilentlyTask;

        signInStatus = signInSilentlyTask.Result.Status;
        if (signInSilentlyTask.Result.Status != SignInStatus.Success)
        {
            TaskYieldInstruction<SignInResult> signInTask = this.XboxLiveUser.User.SignInAsync().AsCoroutine();
            yield return signInTask;

            signInStatus = signInTask.Result.Status;
        }

        // Throw any exceptions if needed.
        if (signInStatus == SignInStatus.Success)
        {
			MainMenumanager.Instance.isSignedInXboxLive = true; // Enable Play button when user has logged into Xbox Live Services
            XboxLive.Instance.StatsManager.AddLocalUser(this.XboxLiveUser.User);
            XboxLive.Instance.PresenceWriter.AddUser(this.XboxLiveUser.User);
            var addLocalUserTask =
                XboxLive.Instance.SocialManager.AddLocalUser(
                    this.XboxLiveUser.User,
                    SocialManagerExtraDetailLevel.PreferredColor).AsCoroutine();
            yield return addLocalUserTask;

            if (!addLocalUserTask.Task.IsFaulted)
            {
                yield return this.LoadProfileInfo();
            }
        }
    }

    private IEnumerator LoadProfileInfo()
    {
        var userId = ulong.Parse(this.XboxLiveUser.User.XboxUserId);
        var group = XboxLive.Instance.SocialManager.CreateSocialUserGroupFromList(this.XboxLiveUser.User, new List<ulong> { userId });
        var socialUser = group.GetUser(userId);

        var www = new WWW(socialUser.DisplayPicRaw + "&w=128");
        yield return null;

        try
        {
            if (www.isDone && string.IsNullOrEmpty(www.error))
            {
                var t = www.texture;
                var r = new Rect(0, 0, t.width, t.height);
                this.gamerpic.sprite = Sprite.Create(t, r, Vector2.zero);
            }

            this.gamertag.text = this.XboxLiveUser.User.Gamertag;
            this.gamerscore.text = socialUser.Gamerscore;

            if (socialUser.PreferredColor != null)
            {
                this.profileInfoPanel.GetComponent<Image>().color =
                    ColorFromHexString(socialUser.PreferredColor.PrimaryColor);
                this.gamerpicMask.color = ColorFromHexString(socialUser.PreferredColor.PrimaryColor);
            }

        }
        catch (Exception ex)
        {
            if (XboxLiveServicesSettings.Instance.DebugLogsOn)
            {
                Debug.Log("There was an error while loading Profile Info. Exception: " + ex.Message);
            }
        }


        this.Refresh();
    }

    public static Color ColorFromHexString(string color)
    {
        var r = (float)byte.Parse(color.Substring(0, 2), NumberStyles.HexNumber) / 255;
        var g = (float)byte.Parse(color.Substring(2, 2), NumberStyles.HexNumber) / 255;
        var b = (float)byte.Parse(color.Substring(4, 2), NumberStyles.HexNumber) / 255;

        return new Color(r, g, b);
    }

    private void Refresh()
    {
        var isSignedIn = this.XboxLiveUser != null && this.XboxLiveUser.User != null && this.XboxLiveUser.User.IsSignedIn;
		MainMenumanager.Instance.isSignedInXboxLive = isSignedIn; // Rechecks and enables play button if user is still logged into Xbox Live services.
        this.signInPanel.SetActive(!isSignedIn);
        this.profileInfoPanel.SetActive(isSignedIn);
    }

    private void OnApplicationQuit()
    {
        XboxLive.Instance.PresenceWriter.StopWriter();
    }
}`

**Comment by johnrlisenby** [comment] 2017-10-20 14:48
I found the problem. I was rechecking user sign-in. It has been working before. The programmer's excuse, LOL

**Comment by johnrlisenby** [comment] 2017-10-21 19:17
Hi Again,
Okay, I fixed the issue within the Unity Editor, but when I build the out the game to test, I'm getting error" ArgumentException. You must add a local user before you can create a social group for them. Parameter name user"

Not sure that the issue is now. None of my code is affecting the Xbox Live user sign and checking for user signing in, 
Any suggestions?

Thanks,
John

**Comment by ayubhassan** [comment] 2017-10-22 03:46
i think you just need to do what the error says. make the user sign in first, then implement a social group.

**Comment by nyarsulik** [comment] 2017-10-22 03:54
My games both stopped working, perhaps we are having the same sign in issues?  I don't do anything with the prefabs, and everything was working great up until a few days ago.  No changes on my side, not sure what happened on the Xbox side outside of the new dashboard, but I thought that was fixed about a month ago when this same thing happened.

**Comment by jasonsandlin** [comment] 2017-10-22 04:04
We will look into this and figure out what's going on. It might be a new issue. In the meantime, are you using QFE 4?

**Comment by moheiji** [comment] 2017-10-22 05:37
I also suffer from similar problems in my environment.
Currently, Example SignInAndProfile also gives an error.

My Development environment
 xbox-live-unity-plugin 1707 QFE 4 Release 

 Unity 5.6.2f1 Personal (64bit) or
 Unity 2017.1.1f1 Personal (64bit) 

 VisualStudio2015

The error message is as follows.

ArgumentException: You must add a local user before you can create a social group for them.
Parameter name: user
> at Microsoft.Xbox.Services.Social.Manager.SocialManager.CreateSocialUserGroupFromList(XboxLiveUseruser.List'1 userIds)
 at UserProfile.<LoadProfileInfo>d__18.MoveNext()
 at UnityEngine.SetupCoroutine.InvokeMoveNext(IEnumerator enumerator,IntPtr returnValueAddress)
 at UnityEngine.SetupCoroutine.$Invoke1(Int64 instance, Int64* args)
at UnityEngine.Internal.$MethodUtility.InvokeMethod(Int64 instance,Int64* args,IntPtr method)

**Comment by johnrlisenby** [comment] 2017-10-22 12:27
I'm using the latest plugin QFE 4.

**Comment by nyarsulik** [comment] 2017-10-23 16:27
@moheiji , it looks like that is also the exact same error I am getting even though the QFE 4 Release had fixed similar issues.  I'll drop off this thread, it seems like this might be a different issue than the OP.

**Comment by MSFT-Heba** [comment] 2017-10-23 22:35
@nyarsulik Could you tell us a bit more about your setup? Are you using the scripts as is? Are you using your own scripts?

**Comment by MSFT-Heba** [comment] 2017-10-23 22:42
@moheiji  Just to double check, are you seeing this issue with the 'SignInAndProfile' scene when you switch out of the scene and back to it? Or are you seeing this the first time you get into that scene?

We want to make sure we are testing the right scenario.

**Comment by johnrlisenby** [comment] 2017-10-23 22:53
Even my game that I published last week it was working, but now its having the same issue. I think its something do with Xbox services. Some setting must have changed. Do you need a test project?

**Comment by MSFT-Heba** [comment] 2017-10-23 23:03
@johnrlisenby We think we may have tracked down the issue, but do need to make sure we're testing all the scenarios you guys are running into. Could you please verify whether you see this issue the first time you go into a scene using Userprofile? or do you see this the next time you get back into the scene?

**Comment by johnrlisenby** [comment] 2017-10-23 23:10
Yes, when the scene first loads with Userprofile prefab. The issue also happen when I navigate back to the same scene.

**Comment by MSFT-Heba** [comment] 2017-10-23 23:18
@johnrlisenby Is there anything special in the setup? Are you using the prefabs as is? Any changes in the scripts? Especially in when/how signin is being called?

Here's how the code flow is happening at the moment:
Basically what is happening that is causing this bug is this line in LoadProfileInfo(): https://github.com/Microsoft/xbox-live-unity-plugin/blob/master/Assets/Xbox%20Live/Scripts/UserProfile.cs#L217

is being called before the SocialManager 'AddLocalUser' is called at: https://github.com/Microsoft/xbox-live-unity-plugin/blob/master/Assets/Xbox%20Live/Scripts/UserProfile.cs#L201

LoadProfileInfo() is only called in two places:
https://github.com/Microsoft/xbox-live-unity-plugin/blob/master/Assets/Xbox%20Live/Scripts/UserProfile.cs#L209
and
https://github.com/Microsoft/xbox-live-unity-plugin/blob/master/Assets/Xbox%20Live/Scripts/UserProfile.cs#L91

**Comment by johnrlisenby** [comment] 2017-10-23 23:25
I removed all my code from the script for testing. Reimported the Unity Package. I added the Xbox Services and Userprofile prefabs to the scene. 

From that point, I am using the defaults from the package. The only thing I added was a bool to check if the user was logged into Xbox Live to enable play button.
Hope this helps.

**Comment by johnrlisenby** [comment] 2017-10-23 23:28
@MSFT-Heba  This lline in LoadProfileInfo(): https://github.com/Microsoft/xbox-live-unity-plugin/blob/master/Assets/Xbox%20Live/Scripts/UserProfile.cs#L217 was the error in Visual Studios during my testing.

**Comment by jasonsandlin** [comment] 2017-10-23 23:30
@johnrlisenby, can you set a breakpoint and tell us the what's calling that function when you hit this error?

**Comment by johnrlisenby** [comment] 2017-10-23 23:51
@jasonsandlin Is that what you are asking for?

 >	Boolean <LoadProfileInfo>c__Iterator2:MoveNext ()+0x46 at N:\Unity Games\TPS Apps\3D Maze Hunter 2017\Assets\Xbox Live\Scripts\UserProfile.cs:218	C#	Symbols loaded.

**Comment by jasonsandlin** [comment] 2017-10-24 00:06
Not quite.  What calls this LoadProfileInfo() function:

https://github.com/Microsoft/xbox-live-unity-plugin/blob/v1707qfe4/Assets/Xbox%20Live/Scripts/UserProfile.cs#L218

Once we know what calls it we should be closer to tracking down which path is causing this.

**Comment by johnrlisenby** [comment] 2017-10-24 00:22
Maybe this >	XboxLiveUser XboxLiveUserInfo:get_User ()+0x0 at N:\Unity Games\TPS Apps\3D Maze Hunter 2017\Assets\Xbox Live\Scripts\XboxLiveUserInfo.cs:18	C#	Symbols loaded.

 	Boolean <LoadProfileInfo>c__Iterator2:MoveNext ()+0x5c at N:\Unity Games\TPS Apps\3D Maze Hunter 2017\Assets\Xbox Live\Scripts\UserProfile.cs:218	C#	Symbols loaded.

 	Void UnityEngine.SetupCoroutine:InvokeMoveNext (IEnumerator, IntPtr)+0x28 at C:\buildslave\unity\build\Runtime\Export\Coroutines.cs:17	C#	Symbols loaded.

**Comment by jasonsandlin** [comment] 2017-10-24 00:47
Hmm, can you put a breakpoints at these spots and see which one is getting hit right before you hit the error:

https://github.com/Microsoft/xbox-live-unity-plugin/blob/v1707qfe4/Assets/Xbox%20Live/Scripts/UserProfile.cs#L90

https://github.com/Microsoft/xbox-live-unity-plugin/blob/v1707qfe4/Assets/Xbox%20Live/Scripts/UserProfile.cs#L207

Thanks

**Comment by johnrlisenby** [comment] 2017-10-24 01:29
@jasonsandlin For line 207 I am getting >	Task TaskYieldInstruction:get_Task ()+0x0 at N:\Unity Games\TPS Apps\3D Maze Hunter 2017\Assets\Xbox Live\Scripts\UnityTaskExtensions.cs:60	C#	Symbols loaded.

 	Boolean <SignInAsync>c__Iterator1:MoveNext ()+0x18c at N:\Unity Games\TPS Apps\3D Maze Hunter 2017\Assets\Xbox Live\Scripts\UserProfile.cs:208	C#	Symbols loaded.
 	Void UnityEngine.SetupCoroutine:InvokeMoveNext (IEnumerator, IntPtr)+0x28 at C:\buildslave\unity\build\Runtime\Export\Coroutines.cs:17	C#	Symbols loaded.


Nothing for line 90

**Comment by johnrlisenby** [comment] 2017-10-24 01:34
@jasonsandlin For my lines in Userprofile I had an extra line at line 200, and that is why my line numbers are off.

**Comment by nyarsulik** [comment] 2017-10-24 01:38
Sorry for the late reply @MSFT-Heba on my question, I am essentially doing the same thing as @johnrlisenby , I am using the prefabs as-is.  In my code I am simply waiting/watching for the ProfileInfo prefab to be enabled and then I reveal my main menu.  This is admittedly probably not the best way to do this.  Since the sign in never completes, the ProfileInfo never gets enabled, and then my menu never gets revealed.  However, within Unity I get the fake ProfileInfo without any errors.  

My PC also fails in the same place (when running through Visual Studio and when running my other games that are already in the store), not just on Xbox One.  My PC is currently running the Windows 10 Pro Insider Preview, 17017.rs_prerelease.171010-1400.  Not sure if that has anything to do with it, but I am guessing not since it is also happening on the Xbox.

My Xbox did get the new dashboard, but I don't think it is "preview".  That is the only other thing that seems like it changed before this stopped working.

**Comment by gmogc-sagawa** [comment] 2017-10-24 01:52
I have also confirmed this error.

> ArgumentException: You must add a local user before you can create a social group for them.
> Parameter name: user
>
> at Microsoft.Xbox.Services.Social.Manager.SocialManager.CreateSocialUserGroupFromList (XboxLiveUseruser.List '1 userIds)
> at UserProfile.d__18.MoveNext ()
> at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress)
> at UnityEngine.SetupCoroutine. $ Invoke 1 (Int64 instance, Int64 * args)
> at UnityEngine.Internal. $ MethodUtility.InvokeMethod (Int64 instance, Int64 * args, IntPtr method)

It's also happening in the SigninAndProfile scene of Example
It is closed problem only with xbox-live-unity-plugin.
Since DevCenter has been informed of a time-limited correction request, we urgently request resolution.

Since the same problem is occurring in Windows 10 Mobile that has not updated the OS as contents checked here
I think that it is due to the change of XboxLIVE.

**Comment by nakfiv** [comment] 2017-10-24 01:53
I have also confirmed this error.

> ArgumentException: You must add a local user before you can create a social group for them.
> Parameter name: user
>
> at Microsoft.Xbox.Services.Social.Manager.SocialManager.CreateSocialUserGroupFromList (XboxLiveUseruser.List '1 userIds)
> at UserProfile.d__18.MoveNext ()
> at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress)
> at UnityEngine.SetupCoroutine. $ Invoke 1 (Int64 instance, Int64 * args)
> at UnityEngine.Internal. $ MethodUtility.InvokeMethod (Int64 instance, Int64 * args, IntPtr method)

It's also happening in the SigninAndProfile scene of Example
It is closed problem only with xbox-live-unity-plugin.
Since DevCenter has been informed of a time-limited correction request, we urgently request resolution.

Since the same problem is occurring in Windows 10 Mobile that has not updated the OS as contents checked here
I think that it is due to the change of XboxLIVE.

**Comment by MSFT-Heba** [comment] 2017-10-24 02:02
Just to confirm, what scripting backend is everyone using? .NET and .NET 2.0?

**Comment by johnrlisenby** [comment] 2017-10-24 03:18
@MSFT-Heba  Correct tried with Net 2.0, Net 2.0 Subset, and 4.6. Same error.

**Comment by moheiji** [comment] 2017-10-24 10:53
@MSFT-Heba The first time I get into that scene.
 I placed only the SignInAndProfile scene on Unity and built it for UWP. There is an error when running on Visualstudio. When running on Unity, a dummy gamertag is displayed.
The same error appears in the game I made.
In this game I have placed the XboxLiveServices prefab and UserProfile prefab in the scene which is loaded first.

**Comment by moheiji** [comment] 2017-10-24 11:43
@MSFT-Heba
My Unity setting:
Scripting Runtime Version Stable(.NET 3.5 equivalent)
Scripting Backend .NET
Api Compativility Level .NET 2.0 Subset

**Comment by TTSSoftware** [comment] 2017-10-25 12:45
Hi, is there an ETA on a fix for this?  I am also having the same problem with my published game.  Will we need to submit a game update or will it be fixed on the back end?

Thanks.

**Comment by digitaldav** [comment] 2017-10-25 13:14
I am having the same problem too. The users can't login, so they can't play my games.

**Comment by MSFT-Heba** [comment] 2017-10-25 18:49
Hello everyone,
We are actively working on this and will provide a fix real soon. Will update this thread with more information as we work on this.

**Comment by nyarsulik** [comment] 2017-10-25 20:03
Thank you @msft-heba and @jasonsandlin!

**Comment by MSFT-Heba** [comment] 2017-10-25 22:29
We believe we have tracked down the issue and a fix will be landing in the service tomorrow that we believe should fix the problem for everyone. There'll be no client changes needed.

We will, also, be doing more testing tomorrow to confirm.

**Comment by MSFT-Heba** [comment] 2017-10-26 19:54
This issue should be fixed now. Please do update us here and confirm.

**Comment by johnrlisenby** [comment] 2017-10-26 20:20
Its working again! Thank you!

John

**Comment by MSFT-Heba** [comment] 2017-10-26 20:23
Perfect! Glad to hear!!

We'll leave this issue open for 24 more hours to make sure we hear from everyone. We'll close this afterwards, but feel free to open up new issues afterwards if you need them.

**Comment by mikeoliphant** [comment] 2017-10-26 21:23
Can you give me some insight into what was changed? All of my games have now stopped working properly.

**Comment by MSFT-Heba** [comment] 2017-10-26 21:43
@mikeoliphant It was a service side fix that resolves an issue with Creators titles using social manager. 

Are you seeing issues still? What errors are you seeing? Which prefabs?

**Comment by mikeoliphant** [comment] 2017-10-26 21:44
Ok, so you fixed the problem where CreateSocialUserGroupFromList was throwing an exception. I was already working around that case.  But now the DisplayPicRaw field of XboxSocialUser is coming back null. I wasn't handling that, and now my games are throwing an exception and breaking.

I can work around this new issue, but I'll have to update all of my games. *Again*. What a nightmare.

**Comment by mikeoliphant** [comment] 2017-10-26 21:46
@MSFT-Heba I am not using any of the prefabs - I'm using the Microsoft.Xbox.Services.UWP.CSharp dll directly.

Do the prefabs currently get the gamer pic correctly? It doesn't seem possible with DisplayPicRaw coming back empty.

**Comment by MSFT-Heba** [comment] 2017-10-26 21:52
@mikeoliphant  This does sound like a different issue. Would you mind opening a new issue for that so we can track it separately? We'll start looking into it though to see if we can repro.

**Comment by TTSSoftware** [comment] 2017-10-26 23:19
The previous problem seems to be resolved for my game and players can at least login now but I am having the same issue with the gamer pic.  I am not using the prefab but my code is based on what the prefab is doing.

**Comment by johnrlisenby** [comment] 2017-10-27 15:50
Update, error has be fixed, but the user doesn't get successful login triggered. In the UserProfile, I am checking if the user has successfully signed in by sending a bool. In the editor, everything works correctly, but when testing PC and Xbox build; this never triggers.

Here is the code `public IEnumerator SignInAsync()
{
    SignInStatus signInStatus;
    TaskYieldInstruction<SignInResult> signInSilentlyTask = this.XboxLiveUser.User.SignInSilentlyAsync().AsCoroutine();
    yield return signInSilentlyTask;

    signInStatus = signInSilentlyTask.Result.Status;
    if (signInSilentlyTask.Result.Status != SignInStatus.Success)
    {
        TaskYieldInstruction<SignInResult> signInTask = this.XboxLiveUser.User.SignInAsync().AsCoroutine();
        yield return signInTask;

        signInStatus = signInTask.Result.Status;
    }

    // Throw any exceptions if needed.
    if (signInStatus == SignInStatus.Success)
    {
		MainMenuManager.Instance.isSignedInXboxLive = true; // Enable Play button when user has logged into Xbox Live Services
        XboxLive.Instance.StatsManager.AddLocalUser(this.XboxLiveUser.User);
        XboxLive.Instance.PresenceWriter.AddUser(this.XboxLiveUser.User);
        var addLocalUserTask =
            XboxLive.Instance.SocialManager.AddLocalUser(
                this.XboxLiveUser.User,
                SocialManagerExtraDetailLevel.PreferredColor).AsCoroutine();
        yield return addLocalUserTask;

        if (!addLocalUserTask.Task.IsFaulted)
        {
            yield return this.LoadProfileInfo();
        }
    }
}
`

New bug?

Thanks,

John

**Comment by MSFT-Heba** [comment] 2017-10-31 02:14
We'll be closing this issue now as resolved.

**Closed by MSFT-Heba** 2017-10-31 02:14 UTC
Labels: bug
