### ISSUE TITLE
StatsManager causing per frame memory allocations

### ISSUE THREAD

**Issue by rygaar72** [Microsoft/xbox-live-unity-plugin#111] opened 2017-08-20 07:16 UTC
I noticed some stuttering in my game, and profiled in the editor to see that the `MockStatsManager.DoWork() `function (called every Update) is doing per frame memory allocations with `this.eventList.ToList()`.  Looking at the code, `StatsManager` will do this as well (although I haven't profiled that yet).

I am pretty sure this is my problem, causing unnecessary stuttering due to garbage collection.

Can the plugin be updated to avoid this?

**Comment by jasonsandlin** [comment] 2017-08-20 08:42
Thanks for the report.  We'll get this fixed

**Comment by rygaar72** [comment] 2017-08-22 18:25
Thanks.  Is there any chance of getting a quick fix for this as it's having a noticeable impact on my released game?

Thanks

**Comment by jasonsandlin** [comment] 2017-08-22 19:31
I'm open to suggestions, but I don't see a quick fix for this.  I think the APIs will have to change to reuse an event pool to avoid garbage collection.  Is that your assessment as well?

**Comment by jasonsandlin** [comment] 2017-08-22 20:10
We're going to work on a fix that returns a static empty list when there's no events (which is most of the time) for both managers.  This should get rid of the perf issue.  We'll send you the change when we have it ready

**Comment by rygaar72** [comment] 2017-08-22 21:26
Yes, that was what I was thinking as a quick fix.  An allocation only when there are events shouldn't really impact gameplay.

thanks Jason, much appreciated.

**Comment by jasonsandlin** [comment] 2017-08-23 00:36
Ok, this fix is in master at https://github.com/Microsoft/xbox-live-unity-plugin/commit/f045305461a0148eff3d42989a9306a450ad570f

Can you build the plugin by following https://github.com/Microsoft/xbox-live-unity-plugin#building and see if it fixes the issue?

Thanks,
Jason

**Comment by rygaar72** [comment] 2017-08-23 21:35
Will do.  I'll have to do this later tonight after work.  Thanks.

**Comment by rygaar72** [comment] 2017-08-23 22:24
I am getting the following error when building:

H:\LiamData\LDC Unity Dev\Packages\xbox-live-unity-plugin-1707qfe1\CSharpSource\Source\Microsoft.Xbox.Services.CSharp.s
ln(136): Solution file error MSB5007: Error parsing the project configuration section in solution file. The entry "" is invalid.

Any ideas?

**Comment by jasonsandlin** [comment] 2017-08-23 23:03
Hmm, I haven't seen this one, but I suspect its because you don't have the C++ components installed in your Visual Studio install.  

I don't see line 136 so not sure what its referring to:
https://github.com/Microsoft/xbox-live-unity-plugin/blob/master/CSharpSource/Source/Microsoft.Xbox.Services.CSharp.sln

**Comment by rygaar72** [comment] 2017-08-24 08:35
Fixed that.  There was a blank line that needed to be deleted for some reason.

Now I am getting:

error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v11.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

I don't have that directory.  Is there something else I need to install?

**Comment by rygaar72** [comment] 2017-08-24 10:34
So I started the whole build again, following the instructions you linked and ended up with the following error:

H:\LiamData\xbox\xbox-live-unity-plugin\CppSource\Build\Microsoft.Xbox.Services.140.UWP.C\Microsoft.Xbox.Services.140.UWP.C.vcxproj(45,3): error MSB4019: The imported project "H:\Microsoft.Cpp.Default.props" was not
found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

**Comment by jasonsandlin** [comment] 2017-08-24 22:18
Not sure what the build issue is.  I can't reproduce it.  

I'll just post the QFE'd asset here so you can just install it: https://github.com/Microsoft/xbox-live-unity-plugin/releases/tag/v1707qfe3

**Closed** 2017-08-24 22:30 UTC
