### ISSUE TITLE
XBOX LIVE CREATOR SAVE FUNCTIONALITY PROBLEM- PLEASE HELP

### ISSUE THREAD

**Issue by tech247** [Microsoft/xbox-live-unity-plugin#114] opened 2017-08-23 12:31 UTC
Hello,
    We are new to Xbox Live Creator program and facing some issues related to Save Functionality. We are using Unity Save data plugin provided by Xbox Live Creator website.

    Issue Faced : We are unable to save our strings value , please tell how to retrieve those values associated with those strings. Please provide link to video tutorial if possible.

    Please help asap, as only this issue is causing our game to be not releasing on time.

    Thanks

**Comment by jasonsandlin** [comment] 2017-08-23 18:39
This is a dupe of https://social.msdn.microsoft.com/Forums/en-US/76ad952d-2467-46db-91ce-4fab40d8f612/xbox-live-creator-save-functionality-problem-please-help?forum=xboxlivedev

We will get back to you there

**Closed by jasonsandlin** 2017-08-23 18:39 UTC
