### ISSUE TITLE
Creators Collection Sign-in on new Xbox Preview home screen is failing for my users

### ISSUE THREAD

**Issue by nyarsulik** [Microsoft/xbox-live-unity-plugin#127] opened 2017-09-14 02:02 UTC
I have a few users who have to go through some weird actions to get the sign-in to work on the Xbox Preview home.  I don't have Preview and can't verify.

The user shared a video, but it cuts out and only has audio where the sign in should happen:
https://onedrive.live.com/?authkey=%21AF1wemooNRlCu%5Fo&cid=96A6173D392240DE&id=96A6173D392240DE%2193621&parId=96A6173D392240DE%2189054&o=OneUp

I am using the standard UserProfile prefab with the latest Xbox Live Plugin.  The only thing I have done differently is specify "joystick 1 button 3" as the input controller button.  This works on the current Xbox home screen.

From the user: "we have to press A+B+LS to start a game but this has to be done quickly".  All that I am doing in my code is waiting for the ProfileInfo to be active, and then I enable my menu, so I am not sure what any of these other presses would be doing.

Any help would be great!

Thanks,
Nick

**Comment by jasonsandlin** [comment] 2017-09-14 20:58
As far as I can tell your saying that on non-preview signin works fine, but on preview builds then signin is busted.  Is that right?  

If so, we'll try to reproduce the issue and see if there was a regression somewhere.

**Comment by nyarsulik** [comment] 2017-09-14 21:04
Yeah, I have about 300 console users, but only the few that I know of that are using the preview dashboard are having strange issues.  It works great on mine and others, but I’m not using preview.

I can send a few free codes for my game as well if that helps, then we might be able to determine if it is localized to just my setup or not.

Thanks!
Nick

Sent from my Windows 10 phone

**Comment by rygaar72** [comment] 2017-09-19 21:44
Any more info on this?  Is this an issue that is going to break all unity games relying on the plugin once the preview dashboard goes live?

**Comment by mikeoliphant** [comment] 2017-09-20 16:19
I am also worried about this. I have had one user report a similar problem, and they also were using the preview dashboard.

**Comment by nyarsulik** [comment] 2017-09-20 16:53
Definitely not happy the issue is there, but I am a little relieved I'm not the only one seeing it.  It is a little frustrating since the issue translates to negative reviews on my game.  @jasonsandlin, have you been able to reproduce this on your side?

**Comment by jasonsandlin** [comment] 2017-09-20 19:33
Nothing to report yet, but we'll get back to you soon

**Comment by rygaar72** [comment] 2017-09-20 21:33
I'm happy to provide a code for my game for testing against the new dashboard if required.  Just let me know.

**Comment by krbroten** [comment] 2017-09-20 22:23
My studio has latest preview access and multiple xbox ones. If you want to DM at krbroten@brotenstudios.ca a code and I can see if the behaviour reproduces on my systems.

That said the latest preview alpha ring has a bunch of dashboard glitches all over it.

**Comment by jasonsandlin** [comment] 2017-09-21 01:12
We can repro this issue.  We're following up with the right team to get this fixed.  Thanks

**Comment by rygaar72** [comment] 2017-09-21 01:54
Will the fix involve changes to the unity plugin?  Or will it be purely in the dashboard / underlying services?

**Comment by jasonsandlin** [comment] 2017-09-21 01:55
It appears to be an OS issue as it works on retail OS, but doesn't on preview OS.

**Comment by rygaar72** [comment] 2017-09-21 02:03
Good to know.  Thanks for the info.

**Comment by mikeoliphant** [comment] 2017-09-21 02:21
Just got another 1-star review because of this :-(  Hopefully it can be resolved soon.

**Comment by mikeoliphant** [comment] 2017-09-21 02:26
I would bet money on this being related to the one-time permissions pop-up that happens for Creators games, but not (to my knowledge) other games.

**Comment by nyarsulik** [comment] 2017-09-25 01:11
Any luck with this Jason?  Sorry for the constant pinging, I am still getting 1-star reviews for this issue only, everyone that gets to play seems to think its great!  :)  There doesn't seem to be a way to inform the preview users that this is an issue, and I am not sure that pulling my game from the list would be a good solution either since I think this is really only a small percentage of the users that have purchased.

**Comment by krbroten** [comment] 2017-09-25 01:43
Preview users are informed when they sign up. That stability issues with os, apps, and games maybe present. If they are complaining they dont understand preview access.

**Comment by mikeoliphant** [comment] 2017-09-25 01:59
That doesn't stop them from leaving 1-star reviews. Maybe preview users shouldn't be allowed to rate games?

**Comment by krbroten** [comment] 2017-09-25 02:21
I would say preview users should not be able to publicly reviews. And only provide testing feedback.

**Comment by mikeoliphant** [comment] 2017-09-25 02:36
I agree. Feedback is useful. Publicly maligning a game because of an issue beyond the developer's control is not.

**Comment by bferrara** [comment] 2017-09-25 16:49
This is some feedback from one of my users:

> I downloaded and launched the game in a VM of W10 version 1607.  Upon launching the game it asked for permission to use the internet.  After granting that permission, the game logged into xbox live successfully.  I was then also able to log into the game on both my W10 preview box, and on the Xbox One S with no issue….so your suspicion in the Github thread is correct – its an issue with the permissions screen not appearing in preview.

Hopefully we get a fix soon because those 1 star reviews are stacking up. 
How about crediting us devs who paid $100 to beta this service along with the expense of long-lasting damage to our review scores?

**Comment by jasonsandlin** [comment] 2017-09-25 19:17
We got the preview consoled OS fixed so this will go away once the fixed console OS rolls out to users which should happen this week.  In the meantime, if you want this fixed right away you can update your game with this release:

https://github.com/Microsoft/xbox-live-unity-plugin/releases/tag/v1707qfe4

It just checks for null or empty on an API that we expected to return null:

https://github.com/Microsoft/xbox-live-unity-plugin/commit/d8f935ca78d911eaae8b15a9322a57feb7efafed

**Comment by mikeoliphant** [comment] 2017-09-25 19:48
Thanks for the update, Jason.

**Comment by nyarsulik** [comment] 2017-09-25 22:37
Awesome, thanks Jason!  I'll try to implement this new version ASAP.

**Comment by mikeoliphant** [comment] 2017-09-26 01:41
If anyone pushes out an update with the fix and has a preview user confirm that it works, please post here and let us know. Thanks!

I temporarily disabled forced login for my games to keep this issue from impacting my users, and I don't want to enable it again until I'm sure it works.

**Comment by mikeoliphant** [comment] 2017-10-03 19:39
Jason - I recently submitted updates to my games with the new Xbox Live plugin. One update passed certification, and two submissions failed with the following reason given:

"On Xbox the app does not respond to the controller. Playing the game is thus impossible."

I am not certain that this is related to the Xbox Live sign-in issue, but it is the only thing I changed in the updates. The games work fine on my Xbox in dev mode. I am not sure where to go from here...

**Comment by nyarsulik** [comment] 2017-10-20 19:36
@jasonsandlin, I think this may have reverted back to failing.  I am now using the newer dashboard and none of my games, even the two that were fixed by this issue about 25 days ago, are no longer signing in.  I noticed this when testing a game I am about to release, but that game was using the same sign in code as my other two.  When I went back to check my other two games they also hang at sign in.  The sign in bubble turns gray like it is trying to do something, but then never moves on.

I haven't had any new reviews saying it's not working, but with today being Friday all of my sales really pickup over the weekend so I am bracing for a new wave of hate.  :|

**Comment by bferrara** [comment] 2017-10-20 20:15
This is definitely back to failing. My game was failed in certification this morning for this reason.

> App Policies: 10.13.5 Xbox Live Active User and Gamertag
> Notes To Developer
> Because your game uses Xbox Live, it must:
>  · Create at least one active user and sign the user into Xbox. 
>  · Display the user’s Xbox gamertag as the primary display and profile name.
> Please add this behavior and resubmit your game.
> 
> Your app keeps loading indefinitely with message "Signing into Xbox Live" after allow access permission.
> 
> You can view the Xbox Live documentation for more information. Your game may not appear in the Creators Collection until this has been resolved.
> Tested Devices: Windows 10 Desktop, Windows 10 Xbox

There are lots of problems at the moment besides this.
The Payout Summary has stopped updating, so even though I've been selling copies, the total has been stuck on the same number for days.

Our app had been on the store after passing certification since Oct 9th without issue, then I get an email that states it failed certification (which I had not initiated) on the 17th for the following reason:

> App Policies: 10.1.1 Inaccurate Representation
> Notes To Developer
> Please disclose any limitations or requirements for input devices in the app description or requirements section and resubmit your app.
> Your app requires touch support for menu navigation, and keyboard + mouse control for gameplay. This is not fully disclosed in metadata.
> 

Our app doesn't support or require touch support. 
I got this response after contacting support about it:

> Thank you for contacting us. It looks like the app may have been failed in error. Please resubmit the app for certification, and it will be reviewed again. 

I added the incorrect limitation statement into the metadata anyhow just to pass certification and that's when I was failed for this Gamertag sign-in issue again.

So, what's the deal?

**Comment by mikeoliphant** [comment] 2017-10-20 20:34
I just updated my dashboard, and my games still seem to work on the new retail dashboard. However, they are no longer able to display the gamer pic, which they used to do just fine. This actually happened at some point recently, but *before* I updated to the new dashboard. I suspect something changed on the Xbox Live server end that is now causing problems with the plugin.

See this thread for the issue that is causing that problem:

https://github.com/Microsoft/xbox-live-unity-plugin/issues/120

I gracefully handle the case where I am not able to create a social user group to get the gamer picture, and just display the gamertag. If your game is relying on getting the gamer picture to proceed, that might be causing it to fail.

**Comment by nyarsulik** [comment] 2017-10-22 03:47
This is still not working and I have already started getting more negative reviews.  Any idea when a fix might be available?  Or, if we can just remove the requirement to have sign in all of my problems would be fixed.

The other comment about the payout summary not updating is happening to me as well.  Is there some sort of global warning to Xbox users that something is broken so they don't think it is our individual games?

**Comment by KarateSnoopy** [comment] 2017-10-22 04:02
We will look into this and figure out what's going on.  It might be a new issue.  In the meantime, are you using QFE 4?

**Comment by jasonsandlin** [comment] 2017-10-22 04:05
We will look into this and figure out what's going on. It might be a new issue. In the meantime, are you using QFE 4?

**Comment by nyarsulik** [comment] 2017-10-23 16:24
Sorry for the late reply, yes, both Block Dropper and Extreme Skeeball were fixed with the QFE4 changes but they now hang while trying to automatically sign in.

Looking now at my new game and it appears I am getting the same ArgumentException as one of the newer issues that was posted: "You must add a local user before you can create a social group for them. Parameter name: user".  My new game is also using QFE4, with essentially the same setup as Extreme Skeeball.

**Comment by jasonsandlin** [comment] 2017-10-23 21:33
Agree with @nyarsulik.  Issue in the OP is fixed so I'm closing this one.  For new issues, please open new issues.  Thanks

**Closed by jasonsandlin** 2017-10-23 21:33 UTC
Labels: bug
